### ISSUE TITLE
Remove changelog file

### ISSUE THREAD

**Issue by fabiante** [DEXPRO-Solutions-GmbH/swaggerui#7]
I noticed that this project maintains a `CHANGELOG` file.

For a small library it is rather annoying having to deal with it and many projects simply don't track changes like this.

We can make use of the [Github Release page](https://github.com/DEXPRO-Solutions-GmbH/swaggerui/releases) which has a feature to automatically generate release notes based on merged PRs.

I want to remove the changelog file in favor of Github releases and the git history.

**Comment by fabiante** [comment]
@Mirco91 What do you think?

**Comment by Mirco91** [comment]
Personally I prefer the github release page, so I'm all for it.
Updating a `CHANGELOG` file tends to be forgotten easily

**Comment by fabiante** [comment]
Nice, I will remove it in a dedicated PR.
